import { useMemo, useState } from 'react'
import type { InventoryItem, JosSettings, OrderRecord, SalesPlanningSettings } from '../types/inventory'
import { calculateSalesProfitPlan, normaliseSalesPlanningSettings, type PlanningAction } from '../lib/salesProfitPlanning'
import { formatFinanceMoney } from '../lib/finance'
import { JosButton, KpiCard, NoticeCard, SectionHeader } from '../ui'
type Props={items:InventoryItem[];orders:OrderRecord[];settings:JosSettings;onChangePlanning:(v:SalesPlanningSettings)=>void;onChangeTarget:(v:number)=>void;onOpenOrders:()=>void;onOpenPipeline:()=>void;onOpenInventory:()=>void;onOpenSourceCheck:()=>void;onOpenFinance:()=>void}
type View='plan'|'simulator'|'health'|'evidence'
function action(a:PlanningAction,p:Props){return a.destination==='orders'?p.onOpenOrders:a.destination==='pipeline'?p.onOpenPipeline:a.destination==='inventory'?p.onOpenInventory:a.destination==='sourcecheck'?p.onOpenSourceCheck:p.onOpenFinance}
export function SalesProfitPlanningCentre(props:Props){
 const [view,setView]=useState<View>('plan');const planning=normaliseSalesPlanningSettings(props.settings.salesPlanning)
 const report=useMemo(()=>calculateSalesProfitPlan(props.items,props.orders,props.settings),[props.items,props.orders,props.settings])
 const update=(key:keyof SalesPlanningSettings,value:number)=>props.onChangePlanning({...planning,[key]:Math.max(0,value)})
 return <main className="screen sales-profit-planning-centre">
  <section className="sp-hero"><div><p className="eyebrow light">SALES & PROFIT PLANNING ENGINE</p><h2>{formatFinanceMoney(report.targetRemaining)} still required</h2><p>{report.daysRemaining} days remain. JOS converts the operating-profit target into sales, listings, stock and daily actions.</p></div><div className={`sp-confidence confidence-${report.confidence}`}><span>Plan confidence</span><strong>{report.confidenceScore}</strong><small>/100 · {report.confidence}</small></div></section>
  <NoticeCard title={`${report.targetLevel} target · ${report.targetProgress}% achieved`} tone={report.paceForecastProfit>=report.monthlyTarget?'positive':'warning'}>{report.confidenceReason}</NoticeCard>
  <section className="jos-kpi-grid sp-kpis"><KpiCard label="Monthly target" value={formatFinanceMoney(report.monthlyTarget)} detail={`${report.daysElapsed} days elapsed`} tone="information"/><KpiCard label="Realised profit" value={formatFinanceMoney(report.realisedProfit)} detail={`${report.realisedSales} recorded sales`} tone={report.realisedProfit>=0?'positive':'urgent'}/><KpiCard label="Pace forecast" value={formatFinanceMoney(report.paceForecastProfit)} detail={`${formatFinanceMoney(report.paceGap)} forecast gap`} tone={report.paceForecastProfit>=report.monthlyTarget?'positive':'warning'}/><KpiCard label="Sales required" value={report.salesRequired} detail={`${report.weeklySalesRequired.toFixed(1)} weekly · ${report.dailySalesRequired.toFixed(1)} daily`} tone="warning"/><KpiCard label="Revenue required" value={formatFinanceMoney(report.revenueRequired)} detail={`${formatFinanceMoney(report.planningAverageSalePrice)} average sale`} tone="information"/><KpiCard label="Average profit plan" value={formatFinanceMoney(report.planningAverageProfit)} detail={report.averageRealisedProfit===undefined?'Saved assumption':'Based on linked sales'} tone={report.averageRealisedProfit===undefined?'warning':'positive'}/></section>
  <section className="sp-tabs">{(['plan','simulator','health','evidence'] as View[]).map(v=><button key={v} className={view===v?'active':''} onClick={()=>setView(v)}>{v==='plan'?'Action plan':v==='simulator'?'What-if':v==='health'?'Health scores':'Evidence'}</button>)}</section>
  {view==='plan'&&<><section className="panel"><SectionHeader eyebrow="TARGET LADDER" title="Progress at every level"/><div className="sp-ladder">{report.targetLadder.map(x=><article className={x.achieved?'achieved':''} key={x.level}><span>{x.level}</span><strong>{formatFinanceMoney(x.target)}</strong><i><b style={{width:`${x.progress}%`}}/></i><small>{x.progress}%</small></article>)}</div></section><section className="panel"><SectionHeader eyebrow="REQUIRED CAPACITY" title="What the target needs from the business"/><div className="sp-capacity"><div><span>Stock capacity required</span><strong>{report.stockRequired}</strong></div><div><span>Launch-eligible stock</span><strong>{report.launchEligibleStock}</strong></div><div><span>Additional stock</span><strong>{report.additionalStockRequired}</strong></div><div><span>Ready listings</span><strong>{report.readyListings}</strong></div><div><span>Additional listings</span><strong>{report.additionalListingsRequired}</strong></div><div><span>Estimated sourcing cost</span><strong>{formatFinanceMoney(report.estimatedSourcingCost)}</strong></div></div></section><section className="panel"><SectionHeader eyebrow="CEO ACTION PLAN" title="Highest-value work now"/><div className="sp-actions">{report.actions.map((a,i)=><article key={a.id}><span>{i+1}</span><div><strong>{a.title}</strong><small>{a.detail}</small></div><JosButton variant="secondary" onClick={action(a,props)}>Open</JosButton></article>)}</div></section></>}
  {view==='simulator'&&<><section className="panel"><SectionHeader eyebrow="WHAT-IF ASSUMPTIONS" title="Test a different operating model" description="These controls change planning assumptions only; they do not edit sales or inventory."/><div className="sp-controls"><label>Average profit per sale<span>£<input type="number" value={planning.assumedAverageProfit} onChange={e=>update('assumedAverageProfit',Number(e.target.value))}/></span></label><label>Sell-through rate<span><input type="number" value={planning.assumedSellThroughRate} onChange={e=>update('assumedSellThroughRate',Number(e.target.value))}/>%</span></label><label>Listings completed per week<span><input type="number" value={planning.assumedListingsPerWeek} onChange={e=>update('assumedListingsPerWeek',Number(e.target.value))}/></span></label><label>Monthly operating-profit target<span>£<input type="number" value={report.monthlyTarget} onChange={e=>props.onChangeTarget(Math.max(0,Number(e.target.value)||0))}/></span></label></div></section><section className="sp-simulator-results"><div><span>Projected month profit</span><strong>{formatFinanceMoney(report.simulator.projectedMonthlyProfit)}</strong></div><div><span>Projected additional sales</span><strong>{report.simulator.projectedSales}</strong></div><div><span>Projected revenue</span><strong>{formatFinanceMoney(report.simulator.projectedRevenue)}</strong></div><div><span>Stock needed</span><strong>{report.simulator.projectedStockNeeded}</strong></div></section></>}
  {view==='health'&&<section className="panel"><SectionHeader eyebrow="BUSINESS HEALTH" title={`${report.health.overall}/100 overall`}/><div className="sp-health">{Object.entries(report.health).filter(([k])=>k!=='overall').map(([k,v])=><article key={k}><span>{k}</span><strong>{v}/100</strong><i><b style={{width:`${v}%`}}/></i></article>)}</div></section>}
  {view==='evidence'&&<><section className="panel"><SectionHeader eyebrow="PLANNING EVIDENCE" title={`${report.confidenceScore}/100 confidence`} description={report.confidenceReason}/><div className="sp-evidence"><div><span>Linked sales this month</span><strong>{report.evidence.linkedSalesThisMonth}</strong></div><div><span>Finance transactions</span><strong>{report.evidence.financeTransactions}</strong></div><div><span>Inventory data quality</span><strong>{report.evidence.inventoryDataQuality}/100</strong></div><div><span>Live listings</span><strong>{report.evidence.liveListings}</strong></div><div><span>Ready listings</span><strong>{report.evidence.readyListings}</strong></div><div><span>Sell-through assumption</span><strong>{report.sellThroughRate}%</strong></div></div></section><section className="sp-assumptions"><p className="eyebrow">PLANNING RULES</p>{report.assumptions.map(a=><p key={a}>{a}</p>)}</section></>}
 </main>
}
