import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
const addItemSource = readFileSync(new URL('./components/AddItem.tsx', import.meta.url), 'utf8')
const automationSource = readFileSync(new URL('./components/AutomationCentre.tsx', import.meta.url), 'utf8')
const backupSource = readFileSync(new URL('./components/BackupCenter.tsx', import.meta.url), 'utf8')
const brandSource = readFileSync(new URL('./components/BrandPerformanceCentre.tsx', import.meta.url), 'utf8')
const forecastSource = readFileSync(new URL('./components/BusinessForecastingCentre.tsx', import.meta.url), 'utf8')
const intelligenceSource = readFileSync(new URL('./components/BusinessIntelligence.tsx', import.meta.url), 'utf8')
const recommendationSource = readFileSync(new URL('./components/CeoRecommendationCentre.tsx', import.meta.url), 'utf8')
const reviewSource = readFileSync(new URL('./components/CeoReviewCentre.tsx', import.meta.url), 'utf8')
const dashboardSource = readFileSync(new URL('./components/Dashboard.tsx', import.meta.url), 'utf8')
const financeSource = readFileSync(new URL('./components/FinanceCommandCentre.tsx', import.meta.url), 'utf8')
const inventorySource = readFileSync(new URL('./components/Inventory.tsx', import.meta.url), 'utf8')
const inventoryEditSource = readFileSync(new URL('./components/InventoryEditCentre.tsx', import.meta.url), 'utf8')
const inventoryIntelligenceSource = readFileSync(new URL('./components/InventoryIntelligenceEngine.tsx', import.meta.url), 'utf8')
const launchSource = readFileSync(new URL('./components/LaunchCommandCentre.tsx', import.meta.url), 'utf8')
const operationsSource = readFileSync(new URL('./components/OperationsCommandCentre.tsx', import.meta.url), 'utf8')
const ordersSource = readFileSync(new URL('./components/Orders.tsx', import.meta.url), 'utf8')
const pipelineSource = readFileSync(new URL('./components/PhotographyListingPipeline.tsx', import.meta.url), 'utf8')
const salesPlanSource = readFileSync(new URL('./components/SalesProfitPlanningCentre.tsx', import.meta.url), 'utf8')
const sourceCheckSource = readFileSync(new URL('./components/SourceCheck.tsx', import.meta.url), 'utf8')
describe('App component completeness', () => {
  it('includes every component imported by App.tsx', () => {
    expect(addItemSource).toContain('export function AddItem')
    expect(automationSource).toContain('export function AutomationCentre')
    expect(backupSource).toContain('export function BackupCenter')
    expect(brandSource).toContain('export function BrandPerformanceCentre')
    expect(forecastSource).toContain('export function BusinessForecastingCentre')
    expect(intelligenceSource).toContain('export function BusinessIntelligence')
    expect(recommendationSource).toContain('export function CeoRecommendationCentre')
    expect(reviewSource).toContain('export function CeoReviewCentre')
    expect(dashboardSource).toContain('export function Dashboard')
    expect(financeSource).toContain('export function FinanceCommandCentre')
    expect(inventorySource).toContain('export function Inventory')
    expect(inventoryEditSource).toContain('export function InventoryEditCentre')
    expect(inventoryIntelligenceSource).toContain('export function InventoryIntelligenceEngine')
    expect(launchSource).toContain('export function LaunchCommandCentre')
    expect(operationsSource).toContain('export function OperationsCommandCentre')
    expect(ordersSource).toContain('export function Orders')
    expect(pipelineSource).toContain('export function PhotographyListingPipeline')
    expect(salesPlanSource).toContain('export function SalesProfitPlanningCentre')
    expect(sourceCheckSource).toContain('export function SourceCheck')
  })
})
